version: "4.28.0"
services:
  web:
    image: nginx:latest
    ports:
      - "8070:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
  php:
    image: php:8-fpm
    volumes:
      - ./code:/code